AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an Amazon ECR repository
Parameters:
  ffEcrRepo:
    Type: String
    Description: Enter a name for the ECR Repository
    Default: 'backend_branch'

Resources:
  ffECRqa:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ffEcrRepo
  MySSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /ffenv/ecrqa              
      Description: My parameter value   
      Type: String                      #
      Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ffECRqa}"           
  MyRegionMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /ffenv/region              
      Description: My parameter value   
      Type: String                      
      Value: !Sub "${AWS::Region}" 
  
  

Outputs:
  ffECRqaName:
    Description: The name of the ECR repository created
    Value: !Ref ffECRqa
    Export:
      Name: ffECRqaName
  ffECRqaUri:
    Description: The URI of the ECR repository created
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ffECRqa}:latest"
    Export:
      Name: ffECRqaUri
  