AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an Amazon ECR repository
Parameters:
  TbEcrRepo:
    Type: String
    Description: Enter a name for the ECR Repository
    Default: 'backend_v2_qa'

Resources:
  TbECRqa:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref TbEcrRepo
  MySSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /tbenv/ecrqa              # Specify the parameter name
      Description: My parameter value   # Optional: Add a description
      Type: String                      # Specify the parameter type (String, SecureString, or StringList)
      Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${TbECRqa}"           # Specify the parameter value
  MyRegionMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /tbenv/region              # Specify the parameter name
      Description: My parameter value   # Optional: Add a description
      Type: String                      # Specify the parameter type (String, SecureString, or StringList)
      Value: !Sub "${AWS::Region}" 
  
  

Outputs:
  TbECRqaName:
    Description: The name of the ECR repository created
    Value: !Ref TbECRqa
    Export:
      Name: TbECRqaName
  TbECRqaUri:
    Description: The URI of the ECR repository created
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${TbECRqa}:latest"
    Export:
      Name: TbECRqaUri
  