AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an ECS cluster, task definition, service, and ALB with target group.

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
               
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/ecs/ff-qa-log-group"
  ECStaskdefSSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /ffenv/ecstask              
      Description: My parameter value   
      Type: String                      
      Value: !Ref ECSTaskDefinition           
  ECSclusternameSSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /ffenv/clustername              
      Description: My parameter value   #
      Type: String                      
      Value: !Ref ECSCluster           



  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ffQATask
      RequiresCompatibilities:
        - FARGATE
      Cpu: "2048"  
      Memory: "8192"  
      NetworkMode: "awsvpc"
      ExecutionRoleArn: "arn:aws:iam::1234567890:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: ffQAContainer
          Image: !ImportValue ffECRqaUri
          Essential: true
          Command:
            - "npm"
            - "run"
            - "start:dev"
          PortMappings:
            - ContainerPort: 3000
              Protocol: "tcp"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/ecs/ff-qa-log-group"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ff-qa-ecs-logs"
Outputs:
  ECSClusterArn:
    Value: !Ref ECSCluster
    Export:
      Name: ff-qa-ECSCluster
  ECSTaskDefinition:
    Description: Task definition.
    Value: !Ref ECSTaskDefinition
    Export:
      Name: ff-qa-ECSTaskDefinition
  
  


