AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create an ECS Service from the ECS Console.
Parameters:  
  ServiceName:
    Type: String
    Default: tb-qa-backend
  
Resources:
  ServnameSSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /tbenv/ecsservicename              # Specify the parameter name
      Description: My parameter value   # Optional: Add a description
      Type: String                      # Specify the parameter type (String, SecureString, or StringList)
      Value: !Ref ServiceName           # Specify the parameter value

  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !ImportValue tb-qa-ECSCluster
      TaskDefinition: !ImportValue tb-qa-ECSTaskDefinition 
      LaunchType: FARGATE
      ServiceName: !Ref ServiceName
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: TbQAContainer
          ContainerPort: 3000
          LoadBalancerName: !Ref 'AWS::NoValue'
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: !Split [",", !ImportValue ECSSecurityGroupARN] 
          Subnets: 
            - !Select [0, !Split [",", !ImportValue TB-qa-PrivateSubnetIds]]  
            - !Select [1, !Split [",", !ImportValue TB-qa-PrivateSubnetIds]]  
            - !Select [2, !Split [",", !ImportValue TB-qa-PrivateSubnetIds]]
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      Tags: []
      EnableECSManagedTags: true
    DependsOn:
      - Listener
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckPath: /api/v1/ping
      HealthCheckTimeoutSeconds: 120   # Updated health check timeout
      HealthCheckIntervalSeconds: 300  # Updated health check interval
      Name: tbqa-backend1
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      VpcId: !ImportValue TB-qa-VPCId 
  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !ImportValue LoadBalancerARN 
      Port: 80
      Protocol: HTTP
Outputs:
  
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
  Listener:
    Description: The created listener.
    Value: !Ref Listener
  TargetGroup:
    Description: The created target group.
    Value: !Ref TargetGroup
